# docker-compose.yml
# Last updated: 2025-06-18 23:01:00

services:
  postgres:
    image: postgres:15
    container_name: calorie_tracker_postgres
    environment:
      POSTGRES_DB: sports_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - calorie_network
    restart: unless-stopped

networks:
  calorie_network:
    driver: bridge
